#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Normal Mode
#bspc monitor DP-0 -d I II III 4 browser
#bspc monitor DP-2 -d 6 music dc

# Game Mode
bspc monitor DP-0 -d I II III 4 browser 6 music dc

bspc config border_width         1
bspc config window_gap           10
bspc config border_radius	 5

bspc config focused_border_color "#F0F0F0"
bspc config normal_border_color  "#000000"
bspc config active_border_color  "#000000"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox state=fullscreen desktop=browser follow=on focus=on
bspc rule -a Spotify state=fullscreen desktop=music follow=off focus=off
bspc rule -a discord state=fullscreen desktop=dc follow=off focus=off
