[manager]
ratio       = [ 1, 2, 3 ]
sort_by     = "natural"
linemode    = "size"
show_hidden = false
scrolloff   = 5

[preview]
tab_size = 4
max_width = 960
# max_height = 900
image_filter = "lanczos3" # nearest, triangle, catmull-rom, lanczos3
image_quality = 90

[opener]
edit = [
	{ run = 'nvim "$@"', block = true },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]

