[shell]
program = "/bin/bash"

[colors.bright]
black = "0x9ea7b3"
blue = "0x91cbff"
cyan = "0x39c5cf"
green = "0x4ae168"
magenta = "0xcb9eff"
red = "0xffb1af"
white = "0xd9dee3"
yellow = "0xf7c843"

[colors.cursor]
cursor = "0xf0f3f6"
text = "0x0a0c10"

[colors.normal]
black = "0x7a828e"
blue = "0x71b7ff"
cyan = "0x39c5cf"
green = "0x26cd4d"
magenta = "0xcb9eff"
red = "0xff9492"
white = "0xd9dee3"
yellow = "0xf0b72f"

[colors.primary]
background = "0x000000"
foreground = "0xffffff"

[window]
opacity = 0.9
startup_mode = "Maximized"

[font]
# normal = { family="MxPlus IBM VGA 9x16"", style="Regular" }
# bold = { family="MxPlus IBM VGA 9x16"", style="Bold" }
# italic = { family="MxPlus IBM VGA 9x16"", style="Italic" }
# bold_italic = { family="MxPlus IBM VGA 9x16"", style="Bold Italic" }

normal = { family="hack", style="Regular" }
bold = { family="hack", style="Bold" }
italic = { family="hack", style="Italic" }
bold_italic = { family="hack", style="Bold Italic" }

size = 20

[cursor]
style = { shape="Block", blinking="Off" }
