#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d I II
bspc monitor DP-2 -d III IV V VI VII

bspc config border_width	2
bspc config window_gap          0
bspc config normal_border_color	"#000000"
bspc config active_border_color	"#000000"
bspc config focused_border_color "#E8E8E8"

bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle		true
bspc config focus_follows_pointer 	true

xset r rate 200 30
