#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII VIIII X
bspc monitor DP-0 music dc web 0 1 2 3 4 5 6 7

bspc config border_width         2
bspc config window_gap           0

bspc config focused_border_color "#F0F0F0"
bspc config normal_border_color  "#000000"
bspc config active_border_color  "#000000"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
